// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opensnitch/rules/rules.proto

package rules // import "github.com/Northern-Lights/os-rules-engine/rules"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action int32

const (
	Action_ACTION_UNKNOWN Action = 0
	Action_ALLOW          Action = 1
	Action_DENY           Action = 2
)

var Action_name = map[int32]string{
	0: "ACTION_UNKNOWN",
	1: "ALLOW",
	2: "DENY",
}
var Action_value = map[string]int32{
	"ACTION_UNKNOWN": 0,
	"ALLOW":          1,
	"DENY":           2,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rules_7d3f9c0681769495, []int{0}
}

// Duration tells how long a rule should apply
type Duration int32

const (
	Duration_DURATION_UNKNOWN Duration = 0
	Duration_ONCE             Duration = 1
	Duration_FIREWALL_SESSION Duration = 2
	Duration_ALWAYS           Duration = 3
)

var Duration_name = map[int32]string{
	0: "DURATION_UNKNOWN",
	1: "ONCE",
	2: "FIREWALL_SESSION",
	3: "ALWAYS",
}
var Duration_value = map[string]int32{
	"DURATION_UNKNOWN": 0,
	"ONCE":             1,
	"FIREWALL_SESSION": 2,
	"ALWAYS":           3,
}

func (x Duration) String() string {
	return proto.EnumName(Duration_name, int32(x))
}
func (Duration) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rules_7d3f9c0681769495, []int{1}
}

// Operation denotes the target to operate upon and how to operate on it
type Operation int32

const (
	Operation_OPERATION_UNKNOWN Operation = 0
	Operation_TRUE              Operation = 9
	Operation_FALSE             Operation = 10
	Operation_AND               Operation = 1
	Operation_OR                Operation = 2
	Operation_NOT               Operation = 3
	Operation_DST_IP            Operation = 4
	Operation_DST_HOST          Operation = 5
	Operation_DST_PORT          Operation = 6
	Operation_PROC_PATH         Operation = 7
	Operation_PID               Operation = 8
)

var Operation_name = map[int32]string{
	0:  "OPERATION_UNKNOWN",
	9:  "TRUE",
	10: "FALSE",
	1:  "AND",
	2:  "OR",
	3:  "NOT",
	4:  "DST_IP",
	5:  "DST_HOST",
	6:  "DST_PORT",
	7:  "PROC_PATH",
	8:  "PID",
}
var Operation_value = map[string]int32{
	"OPERATION_UNKNOWN": 0,
	"TRUE":              9,
	"FALSE":             10,
	"AND":               1,
	"OR":                2,
	"NOT":               3,
	"DST_IP":            4,
	"DST_HOST":          5,
	"DST_PORT":          6,
	"PROC_PATH":         7,
	"PID":               8,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rules_7d3f9c0681769495, []int{2}
}

type Rule struct {
	Action               Action      `protobuf:"varint,1,opt,name=action,proto3,enum=opensnitch.rules.Action" json:"action,omitempty"`
	Duration             Duration    `protobuf:"varint,2,opt,name=duration,proto3,enum=opensnitch.rules.Duration" json:"duration,omitempty"`
	Condition            *Expression `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_rules_7d3f9c0681769495, []int{0}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_ACTION_UNKNOWN
}

func (m *Rule) GetDuration() Duration {
	if m != nil {
		return m.Duration
	}
	return Duration_DURATION_UNKNOWN
}

func (m *Rule) GetCondition() *Expression {
	if m != nil {
		return m.Condition
	}
	return nil
}

// Expression is used to decide whether a connection matches a condition.
// It can be made up of 1 other expression (e.g. for NOT) or 2 other expressions
// (e.g. for AND or OR,) or it can be a "leaf" expression specifying a primitive
// type upon which to operate. The language-specific implementation should
// select the correct field based on the operation
type Expression struct {
	Name                 string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Operation            Operation   `protobuf:"varint,1,opt,name=operation,proto3,enum=opensnitch.rules.Operation" json:"operation,omitempty"`
	Left                 *Expression `protobuf:"bytes,14,opt,name=left,proto3" json:"left,omitempty"`
	Right                *Expression `protobuf:"bytes,15,opt,name=right,proto3" json:"right,omitempty"`
	Strings              []string    `protobuf:"bytes,2,rep,name=strings,proto3" json:"strings,omitempty"`
	Uint32S              []uint32    `protobuf:"varint,3,rep,packed,name=uint32s,proto3" json:"uint32s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_rules_7d3f9c0681769495, []int{1}
}
func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (dst *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(dst, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

func (m *Expression) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Expression) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_OPERATION_UNKNOWN
}

func (m *Expression) GetLeft() *Expression {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *Expression) GetRight() *Expression {
	if m != nil {
		return m.Right
	}
	return nil
}

func (m *Expression) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *Expression) GetUint32S() []uint32 {
	if m != nil {
		return m.Uint32S
	}
	return nil
}

func init() {
	proto.RegisterType((*Rule)(nil), "opensnitch.rules.Rule")
	proto.RegisterType((*Expression)(nil), "opensnitch.rules.Expression")
	proto.RegisterEnum("opensnitch.rules.Action", Action_name, Action_value)
	proto.RegisterEnum("opensnitch.rules.Duration", Duration_name, Duration_value)
	proto.RegisterEnum("opensnitch.rules.Operation", Operation_name, Operation_value)
}

func init() { proto.RegisterFile("opensnitch/rules/rules.proto", fileDescriptor_rules_7d3f9c0681769495) }

var fileDescriptor_rules_7d3f9c0681769495 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0x8b, 0xda, 0x4c,
	0x14, 0x87, 0xdf, 0x49, 0x62, 0x4c, 0xce, 0xdb, 0xb5, 0xd3, 0x43, 0x0b, 0xa1, 0xdd, 0x0b, 0xd9,
	0x2b, 0x11, 0xfc, 0x53, 0x17, 0x0a, 0xed, 0xdd, 0xd4, 0x64, 0x59, 0x69, 0x98, 0x09, 0x93, 0x88,
	0x6c, 0x6f, 0xc4, 0x75, 0xa7, 0x1a, 0x70, 0x27, 0x92, 0x44, 0xe8, 0xd7, 0xe8, 0xf7, 0xe8, 0xd7,
	0xeb, 0x7d, 0x49, 0xd4, 0x15, 0xd6, 0x5e, 0xec, 0x8d, 0xcc, 0x99, 0xdf, 0xf3, 0x1c, 0x8e, 0x27,
	0x0c, 0x5c, 0x66, 0x5b, 0xa5, 0x0b, 0x9d, 0x96, 0xcb, 0xf5, 0x20, 0xdf, 0x6d, 0x54, 0xb1, 0xff,
	0xed, 0x6f, 0xf3, 0xac, 0xcc, 0x90, 0x9e, 0xd2, 0x7e, 0x7d, 0x7f, 0xf5, 0x9b, 0x80, 0x25, 0x77,
	0x1b, 0x85, 0x43, 0xb0, 0x17, 0xcb, 0x32, 0xcd, 0xb4, 0x47, 0xda, 0xa4, 0xd3, 0x1a, 0x79, 0xfd,
	0xe7, 0x6c, 0x9f, 0xd5, 0xb9, 0x3c, 0x70, 0xf8, 0x09, 0x9c, 0x87, 0x5d, 0xbe, 0xa8, 0x1d, 0xa3,
	0x76, 0xde, 0x9f, 0x3b, 0xfe, 0x81, 0x90, 0x4f, 0x2c, 0x7e, 0x01, 0x77, 0x99, 0xe9, 0x87, 0xb4,
	0x16, 0xcd, 0x36, 0xe9, 0xfc, 0x3f, 0xba, 0x3c, 0x17, 0x83, 0x9f, 0xdb, 0x5c, 0x15, 0x45, 0xa5,
	0x9e, 0xf0, 0xab, 0x3f, 0x04, 0xe0, 0x94, 0x20, 0x82, 0xa5, 0x17, 0x8f, 0xca, 0xb3, 0xda, 0xa4,
	0xe3, 0xca, 0xfa, 0x8c, 0x9f, 0xc1, 0xcd, 0xb6, 0xea, 0x30, 0xd7, 0xfe, 0xbf, 0x7c, 0x38, 0x6f,
	0x2f, 0x8e, 0x88, 0x3c, 0xd1, 0x38, 0x04, 0x6b, 0xa3, 0x7e, 0x94, 0x5e, 0xeb, 0x05, 0x43, 0xd5,
	0x24, 0x8e, 0xa0, 0x91, 0xa7, 0xab, 0x75, 0xe9, 0xbd, 0x7e, 0x81, 0xb2, 0x47, 0xd1, 0x83, 0x66,
	0x51, 0xe6, 0xa9, 0x5e, 0x15, 0x9e, 0xd1, 0x36, 0x3b, 0xae, 0x3c, 0x96, 0x55, 0xb2, 0x4b, 0x75,
	0x79, 0x3d, 0x2a, 0x3c, 0xb3, 0x6d, 0x76, 0x2e, 0xe4, 0xb1, 0xec, 0x7e, 0x04, 0x7b, 0xbf, 0x7d,
	0x44, 0x68, 0xb1, 0x71, 0x32, 0x11, 0x7c, 0x3e, 0xe5, 0xdf, 0xb8, 0x98, 0x71, 0xfa, 0x1f, 0xba,
	0xd0, 0x60, 0x61, 0x28, 0x66, 0x94, 0xa0, 0x03, 0x96, 0x1f, 0xf0, 0x3b, 0x6a, 0x74, 0x43, 0x70,
	0x8e, 0xcb, 0xc7, 0xb7, 0x40, 0xfd, 0xa9, 0x64, 0xcf, 0x34, 0x07, 0x2c, 0xc1, 0xc7, 0x01, 0x25,
	0x55, 0x7e, 0x33, 0x91, 0xc1, 0x8c, 0x85, 0xe1, 0x3c, 0x0e, 0xe2, 0x78, 0x22, 0x38, 0x35, 0x10,
	0xc0, 0x66, 0xe1, 0x8c, 0xdd, 0xc5, 0xd4, 0xec, 0xfe, 0x22, 0xe0, 0x3e, 0xed, 0x0c, 0xdf, 0xc1,
	0x1b, 0x11, 0x05, 0xff, 0x6a, 0x98, 0xc8, 0x69, 0x40, 0xdd, 0x6a, 0xa2, 0x1b, 0x16, 0xc6, 0x01,
	0x05, 0x6c, 0x82, 0xc9, 0xb8, 0x4f, 0x09, 0xda, 0x60, 0x08, 0x49, 0x8d, 0xea, 0x82, 0x8b, 0x84,
	0x9a, 0x55, 0x7f, 0x3f, 0x4e, 0xe6, 0x93, 0x88, 0x5a, 0xf8, 0x0a, 0x9c, 0xea, 0x7c, 0x2b, 0xe2,
	0x84, 0x36, 0x8e, 0x55, 0x24, 0x64, 0x42, 0x6d, 0xbc, 0x00, 0x37, 0x92, 0x62, 0x3c, 0x8f, 0x58,
	0x72, 0x4b, 0x9b, 0x95, 0x1f, 0x4d, 0x7c, 0xea, 0x7c, 0x1d, 0x7d, 0x1f, 0xae, 0xd2, 0x72, 0xbd,
	0xbb, 0xef, 0x2f, 0xb3, 0xc7, 0x01, 0xcf, 0xf2, 0x72, 0xad, 0x72, 0xdd, 0x0b, 0xab, 0x2d, 0x17,
	0x83, 0xac, 0xe8, 0xd5, 0x5f, 0xa0, 0xa7, 0xf4, 0x2a, 0xd5, 0x6a, 0xff, 0x0e, 0xee, 0xed, 0xfa,
	0x21, 0x5c, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x46, 0x26, 0x50, 0x79, 0x28, 0x03, 0x00, 0x00,
}
